spring:

  application:
    name: musinsa
#  thymeleaf:
#    prefix: templates/
#    suffix: .html
#    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Wjdfyddn2015!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # 설정 중요.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: zzzzzzzzzzzzzzzzzzzzzzsssssssssssssssssssssssssssddddddddddddddddddddddddddd

  security:
    oauth2:
      client:
        # registration 필수 - 외부 서비스에서 우리 서비스를 특정하기 위해 등록하는 정보.
        registration:

          # Naver - https://developers.naver.com/docs/login/overview/overview.md
          naver:
            client-name: naver
            client-id: z3RNBs6FUajd94AGnOHP
            client-secret: 9_7ZFA_MWS
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # 코드 발급 받을 uri
            authorization-grant-type: authorization_code # 받아올 코드 방식
            scope:
              - name
              - email # 받아올 값.

          # Google -https://console.cloud.google.com
          google:
            client-name: google
            client-id: 645917480509-bcij54pthrsmcgcp7mk1a8cbt4tkhlej.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # 코드 발급 받을 uri
            authorization-grant-type: authorization_code # 받아올 코드 방식
            scope: profile, email # 받아올 값.


        # provider - 구글, Okta, facebook, github 등은 내부적으로 provider 데이터를 가지고 있음
        # ClientRegistration 클래스로도 다룰 수 있음.
        provider:

          # Naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          # Google - 구글은 provider가 자동으로 넣어짐.


  data:
    redis:
      host: 192.168.56.101
      port: 6379